spring:  
  jpa:
    hibernate:  
      ddl-auto: update  
    properties:  
      hibernate:  
        dialect: org.hibernate.dialect.MySQL8Dialect  
    open-in-view: false
  datasource:  
    url: jdbc:mysql://localhost:3306/test_prep 
    username: root  
    password: root